### ISSUE TITLE
Tolerance issues at different zoom levels

### ISSUE THREAD

**Issue by laurenoldham1202** [bemky/mapbox-gl-draw-freehand-mode#11]
Hi there!

I'm trying to use this freehand mode plugin for my project and I'm getting errors at small-scale views, e.g. zoom levels ~0-4. 

You can replicate the error in the official plugin demo: https://bemky.github.io/mapbox-gl-draw-freehand-mode/

- Zoom out to a small scale zoom level (0-4)
- Draw a shape on the map with freehand mode
- Release your mouse/mouseup -> error occurs in console, draw mode gets 'stuck' on point of mouseup (it can be released with a double click, but still generates the error first)

<img width="1787" alt="Screen Shot 2021-06-08 at 10 41 47 AM" src="https://user-images.githubusercontent.com/16802979/121206041-22ad9800-c846-11eb-9c66-6577f616bf94.png">

The console logs the error from @turf/turf/simplify: 
```
Uncaught Error: invalid tolerance
    at Me (main.es.js:167)
    at Q.ke.onMouseUp (index.js:52)
    at Object.<anonymous> (object_to_mode.js:33)
    at n (mode_handler.js:40)
    at Object.mouseup (mode_handler.js:88)
    at n.mouseup (events.js:72)
    at n.It.fire (mapbox-gl.js:31)
    at n.fire (setup.js:52)
    at Ri.mouseup (mapbox-gl.js:35)
    at gn.handleEvent (mapbox-gl.js:35)
```

The issue stems from the code:
```
var tolerance = (3 / ((this.map.getZoom()-4) * 150)) - 0.001 // https://www.desmos.com/calculator/b3zi8jqskw 
simplify(state.polygon, {
    mutate: true,
    tolerance: tolerance,
    highQuality: true 
});
```

I played around with it locally, and when you take out this tolerance, small-scale drawings work, BUT large-scale (zoomed-in) drawings now fail.

Is there a way to set the tolerance so that both small and large-scale shapes can be drawn on the map with freehand mode error-free?

**Comment by bemky** [comment]
I'll take a look. There are few open issues about this tolerance calculation.

**Comment by bemky** [comment]
I just pushed a new release, that I believe fixes this problem
https://github.com/bemky/mapbox-gl-draw-freehand-mode/releases/tag/2.1.0

**Comment by laurenoldham1202** [comment]
> I just pushed a new release, that I believe fixes this problem
> https://github.com/bemky/mapbox-gl-draw-freehand-mode/releases/tag/2.1.0

Fantastic! This seems to do the trick. :) One caveat is that in my actual code, I had to update my event handlers because this fired both `draw.update` and `draw.create` for each drawn shape.

**Comment by bemky** [comment]
Interesting, I assume Mapboxes `DrawPolygon` functions the same way. I didn't really change anything that would have changed how events are fired.
