### ISSUE TITLE
I am always get a triangle as a result

### ISSUE THREAD

**Issue by benderlidze** [bemky/mapbox-gl-draw-freehand-mode#2]
Hi.
Thanks fo great lib.
Can you have a look at this fiddle 
http://jsfiddle.net/oe2gus75/9/

I am always get a triangle as a result of free draw.
Maybe the problem is in mapbox or mapbox-draw version?
Thanks.

**Comment by bemky** [comment]
The method that simplifies the geometry is probably too simplified at a close zoom level. You'll see the further you zoom out the less simplified the geometry is.

The method for simplifying is here: https://github.com/bemky/mapbox-gl-draw-freehand-mode/blob/master/src/index.js#L47

I'll see if I can rework to better adapt to zoom levels.

**Comment by benderlidze** [comment]
Thanks.
But if I hardcode the tolerance = 0.003 it is still the same result. 
But should work fine as I get tolerance 0.003 on zoom level 12

**Comment by benderlidze** [comment]
Hi @bemky.
Any updates on this?
Or any help with this 

> But if I hardcode the tolerance = 0.003 it is still the same result.
But should work fine as I get tolerance 0.003 on zoom level 12

Thanks

**Comment by johnniehard** [comment]
I had this same issue, but only on mobile. I went for simply disabling the simplification step.

**Comment by bemky** [comment]
sorry guys, I've been super covered up with work and life... the method for simplification needs to be tweaked. I welcome any PR if you guys have time.

**Comment by edanweis** [comment]
> I had this same issue, but only on mobile. I went for simply disabling the simplification step.

Could you please tell me how you removed the simplify method? I'm having the [same issue](https://github.com/mapbox/mapbox-gl-draw/issues/883)

Edit: this seems to have fixed it: [https://github.com/edanweis/mapbox-gl-draw-freehand-mode/commit/d14f7897f8f10b679a75f3974fcb146f7f368d2d](https://github.com/edanweis/mapbox-gl-draw-freehand-mode/commit/d14f7897f8f10b679a75f3974fcb146f7f368d2d)

**Comment by DjKhireddine** [comment]
Hi guys, 
I had the same problem. I had a triangle with each drawing (big zoom).
My solution was to set tolerance to 0.000001, you can ajust it as needed (depending on the most used zoom).
`FreeDraw.onMouseUp = function (state, e) {
            if (state.dragMoving) {
                //var tolerance = 3 / ((this.map.getZoom() - 4) * 150) - 0.001; // https://www.desmos.com/calculator/b3zi8jqskw
                (0, _simplify2.default)(state.polygon, {
                    mutate: true,
                    tolerance: 0.000001,
                    highQuality: true
                });

                this.fireUpdate();
                this.changeMode(_constants2.default.modes.SIMPLE_SELECT, { featureIds: [state.polygon.id] });
            }
        };`

**Comment by DjKhireddine** [comment]
Hi guys,
I had the same problem. I had a triangle with each drawing (big zoom).
My solution was to set tolerance to 0.000001, you can ajust it as needed (depending on the most used zoom).

FreeDraw.onMouseUp = function (state, e) {
            if (state.dragMoving) {
                (0, _simplify2.default)(state.polygon, {
                    mutate: true,
                    tolerance: 0.000001,
                    highQuality: true
                });

                this.fireUpdate();
                this.changeMode(_constants2.default.modes.SIMPLE_SELECT, { featureIds: [state.polygon.id] });
            }
 }

**Comment by webberig** [comment]
The problem is caused by simplify. I installed the latest version of `@turf/simplify` (6.3.0), used that one in my own `onMouseUp` function and now I got some more expected results from simplify.

**Comment by bemky** [comment]
I just pushed a new release that refactors the tolerance algorithm used for the simplify method. This release also makes it possible to define your own simplify message when using.

#### Example removing simplification
```javascript
import FreehandMode from 'mapbox-gl-draw-freehand-mode';

FreehandMode.simplify = function (polygon, zoom) {}
```

#### Example with your own tolerance calculation
```javascript
import FreehandMode from 'mapbox-gl-draw-freehand';

FreehandMode.simplify = function (polygon, zoom) {
    simplify(polygon, {
        mutate: true,
        tolerance: 1 / Math.pow(2, zoom),
        highQuality: true
    });
}
```
