### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by tomasdev** [bemky/mapbox-gl-draw-freehand-mode#5]
Moving the created area around re-renders the border every frame. This results in a very laggy experience. It shouldn't re-calculate the border dashes if zoom hasn't changed and the user is just moving it (same shape)

You can really see this behavior when dragging a created polygon vertically

**Comment by bemky** [comment]
Can we get a recheck on this? I pushed some updates today, that may have helped. Please reopen if you still notice issue. I tried myself and was unable to recreate.
