### ISSUE TITLE
Freehand draw  is not working in angular 6

### ISSUE THREAD

**Issue by malaytrivedisa** [bemky/mapbox-gl-draw-freehand-mode#7]
I get this type of warning in console

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
11:14-23 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
14:18-27 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
24:34-43 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
25:26-35 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
39:34-43 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
55:24-33 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
64:18-27 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

WARNING in ./node_modules/mapbox-gl-draw-freehand-mode/src/index.js
65:16-25 "export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

**Comment by caiusCitiriga** [comment]
@bemky any news on this? I have the same exact problem with Angular 10, and cannot find a way to get rid of it 😢

**Comment by bemky** [comment]
@caiusCitiriga I'm not entire sure how to fix, but I have some ideas that change up how to setup using it. My plate is full right now so it might be a week or so until I can dig in.

**Comment by caiusCitiriga** [comment]
> @caiusCitiriga I'm not entire sure how to fix, but I have some ideas that change up how to setup using it. My plate is full right now so it might be a week or so until I can dig in.

Hey @bemky no problem, I can wait 😊 
The exact error is this one: 
```
ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 11:14-23
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 14:18-27
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 24:34-43
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 25:26-35
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 39:34-43
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 55:24-33
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'

ERROR in /Users/caiuscitiriga/Code/topevo/ShellyStack/frontend/webviews-workspace/node_modules/mapbox-gl-draw-freehand-mode/src/index.js 64:18-27
"export 'default' (imported as 'Constants') was not found in '@mapbox/mapbox-gl-draw/src/constants'
```

And as additional detail, I've noticed that there are some references to `@mapbox/mapbox-gl-draw-freehand-mode` but looking inside the `node_modules` there's nothing like that in the `@mapbox` folder, instead it has its own folder outside of `@mapbox`. Not sure if it can help... 

Can you ping me once you can start working on this? I'm very happy to help in any way for what I can 😊

**Comment by raffiar** [comment]
Hey. Is there any updates?

**Comment by bemky** [comment]
Yes, I believe I have a fix in place. Still working on testing. I hope to have it out this week.
