### ISSUE TITLE
Current demo is broken

### ISSUE THREAD

**Issue by caiusCitiriga** [bemky/mapbox-gl-draw-freehand-mode#8]
The currently published demo is not working:

**on load:**
`Uncaught ReferenceError: Constants is not defined`

**on mouse interaction:**
`index.js:1 Uncaught TypeError: Cannot read property 'mouseout' of null`
`index.js:1 Uncaught TypeError: Cannot read property 'mousemove' of null`
`index.js:1 Uncaught TypeError: Cannot read property 'mousedown' of null`
`index.js:1 Uncaught TypeError: Cannot read property 'drag' of null`

**Comment by bemky** [comment]
Maybe I messed up the build on github pages. I’ll check into it today.

**Comment by lucasprograms** [comment]
@bemky did you find a resolution to this? Is the package still working generally?

**Comment by bemky** [comment]
It is working fine for me in development. I think the demo on GitHub hasn’t been updated to the latest. I’m working to resolve that

**Comment by bemky** [comment]
Yes, I think I failed to update `/docs` when I setup webpack. It's fixed now. The demo should work. The build should have already been working. Thanks for heads up!
